fixed some minor errors
linted/linuxprivchecker pull request #16
Opened 2018-03-05 05:23 UTC by alibkaba

fixed some minor errors

2018-03-11 01:15 UTC, linted commented on linuxprivchecker.sh
> +  cmdRESPONSE "find / \( -wholename '/home/homedir*' -prune \) -o \( -type d -perm -0002 \) -exec ls -ld '{}' ';' | grep -v root";
hey while you are at it, why is it pruning the weird `/home/homedir*` part? I feel like that dir is completely non standard and personally I would love to know if I can write to another users home dir... This goes for line 176 too.

2018-03-11 01:16 UTC, linted requested changes
Review my comments and tell me your thoughts please!

2018-03-12 04:30 UTC, alibkaba commented on linuxprivchecker.sh
> +  cmdRESPONSE "find / \( -wholename '/home/homedir*' -prune \) -o \( -type d -perm -0002 \) -exec ls -ld '{}' ';' | grep -v root";
@linted I actually I don't know, it has always been there.  We can certainly make it look better.
When I have time later this week, I will look into it.

2018-10-05 23:39 UTC, linted approved these changes

2018-10-05 23:41 UTC, merged