Update linuxprivchecker.sh
linted/linuxprivchecker pull request #8
Opened 2018-01-07 07:08 UTC by alibkaba

I made quite a few changes to this script by merging it with my own version.  I'm all hears for suggestions and my feelings won't get hurt if it gets rejected.  I've learned a lot from the original script written folks here. @5aru @linted 

I don't need this to be merged in yesterday.  Please, take your time to review it and test.  I'll be doing the same while I prepare for my OSCP exam I have in 2 weeks.

2018-01-08 01:41 UTC, 5aru commented
Hey @alibkaba, I like what you've done. You definitely put it a bit of work. 

I've downloaded the patch and have run it on a VM just to make sure that everything works fine. I've also stepped through the code to review the changes. 

There is one change that I am a little concerned about and another that is _mostly_ preference. 

**Concern**
You've added a cleanUP function to try and clear logs on the system. This sounds nice, but the problem is that in any engagement, you want to try and maintain as much opsec as you can. By using this script and putting it on the system in the first place, you are already breaching opsec and have to make sure to clean this file off of the system. By automatically trying to delete these logs, you run the risk of alerting administrators, setting off IDS/IPS or FIMS and ruining lots of data that could be useful to you as well as the administrators.

On a note, if I noticed that logs were missing out of my own systems. I would immediately triage my system and start looking at the network to see if I could find out what happened.

**Preference**
I enjoy the colors that you've added and how you've modified some of the formatting. In _"Related Shell Escape Sequences"_ though, it jumps a lot when working through the section(s). If that could be consolidated into one solid section for both organization and appearance, that'd be preferred. 

When we originally ported this script over, we did it in such a way that we would keep the formatting of the old privilege escalation checking script that is so well known in the pentesting community, but I like what you've done with the appearance.

Let me know what you think.

2018-01-08 03:53 UTC, linted requested changes

2018-01-08 03:53 UTC, linted commented on linuxprivchecker.sh
> +  systemNAME="Clearing /var/log/auth.log";
I think I have to agree with @5aru. Simply wiping those files away is probably not the best way of cleaning up. If you can think up a good way to do a regex to filter out only the logs this script creates, that would be ideal. Otherwise we should leave log cleaning up to the person running the script.

2018-01-08 03:53 UTC, linted commented on linuxprivchecker.sh
> +  cmdRESPONSE "export HISTFILESIZE=0";
It is probably not the best Idea to clear the history. I know that personally if I logged into one of my boxes and there was no history, I would start to be suspicious of what could have happened. In my opinion you should remove everything in the cleanup except for lines 260 and 261 which should move to the beginning somewhere. Also the exports that you are doing here are probably useless unless people are sourcing this file. feel free to argue your point.

2018-01-08 04:54 UTC, alibkaba commented on linuxprivchecker.sh
> +  systemNAME="Clearing /var/log/auth.log";
Good point, I totally agree with this.  I added this function in the early stages of my pen testing experience (and off a book).

2018-01-08 04:56 UTC, alibkaba commented on linuxprivchecker.sh
> +  cmdRESPONSE "export HISTFILESIZE=0";
Also agree.

2018-01-08 04:58 UTC, alibkaba commented
@5aru @linted Thanks for the feedback.
I've never made changes to a Pull Request, so bare with me while I figure it out and sorry ahead of time for creating duplicate PR.

2018-01-08 06:04 UTC, alibkaba commented
I got a question @5aru @linted.
When you guys write your script, do you think about the compatibility between newer and older bash versions?

I'm worry that these might not work on older bash version and I tried to look for the manual but I only see the latest one.
line 72 ${PIPESTATUS[0]}, line 75 ${cmdRESULT:(-1)}, line 77/80 ${cmdRESULT%?}.
https://www.gnu.org/software/bash/manual/

Comments, suggestions would be appreciated.

2018-01-10 01:20 UTC, 5aru commented on linuxprivchecker.sh
>    fi
Rouge `fi`

2018-01-10 01:20 UTC, 5aru commented on linuxprivchecker.sh
>    fi
Rouge `fi`

2018-01-10 01:24 UTC, 5aru commented
@alibkaba, I really haven't looked into that, but how about we put that into another pull request instead of this one. They are definitely different issues.

I'm going to approve this pull request and I'll just jump in and kill the rouge `fi` at the end of the document...

Thanks for all the work.

2018-01-10 01:25 UTC, merged

2018-01-10 20:05 UTC, alibkaba commented
Okay @5aru .  I just discovered what Travis does and learning it at work, so my code might get a little better. 
Just to be safe, could we revert back to the old version so that I further test my code.
Thanks for the feedbacks and all.

2018-01-10 20:32 UTC, 5aru commented
@alibkaba, I've reverted the old pull request per your request.

2018-01-10 20:35 UTC, alibkaba commented
Thanks @5aru , I just want to make sure I thoroughly test the my crappy code.
Thanks!

2018-01-11 04:00 UTC, alibkaba commented
@5aru @linted I gotta say, I wish I knew Travis CI years ago...I've been doing everything manually and it has been time consuming.
I got couple areas I need to fix but I'll update everyone once I'm done or need suggestions.